export const names = [
  'Abraham E. Hanson',
 
  'Adaibo Recheal',
  'Adasi Hebron Stephen',
  'Agala Esau Jessica',
  // 'Agala Esau Prophetess',
  'Angelina Ishmael',
  'Apollos Ebirien',
  'Atamgbo Dike',
  'Ataisi Derefah',
  'Ataije Awajiokaan-uche Victor',
  'Atanfut David Inyong',
  'Awor Romgbo-okanbe',
  'Ayauwu Ayauwu Loveday',
  // 'Ayauwu Loveday',
  'Benice Monday',
  'Benice Okwa-gwun',
  // 'Blacky Blacky James',
  'Caroline Gogo Jonathan',
  'Charles Mbet',
  'Cheta Ester Friday',
  'Comfort Joshua',
  'Daniel Ferdinard',
  'Daniel Miracle',
  // 'David Samuel',
  'David Samuel Nichodemus',
  'Delight Samuel',
  'Dimkpa Dike',
  'Dimkpa Selinah',
  'Dorcas Ataisi',
  'Ebge Ephraim Egbe',
  'Ebirien-uket Awajimijaan Thompson',
  'Ebirien-uket Rose Thomson',
  'Ebirien Matthew Longjohn',
  'Elizabeth Kasirotu Gwom-ibibaan',
  'Ephraim Egbe',
  'Ephraim Lawrence',
  'Eriente Inyene Martha',
  
  'Emenike Simon Jonah',
  'Eneawaji Uchente Ataisi',
  'Ene Ugbanawaji',
  'Eneigakikpon',
  'Enos Zaccheaus J.',
  'Etonawaji',
  'Evelyn Ignatius',
  'Ezen Atamgbo',
  'Ezen Idabite',
  'Famous Uche.',
  'Festa Awajionyi',
  'Fingesi Fingesi',
  'Friday John',
  'Gabriel Uche Owupele',
  'Garrick Evelyn Itesi',
  'Garrick Mary Itesi',
  'George Awajimam',
  'Glory Randolf',
  "God'sgift Sampson Akpan",
  'Godgift Sampson',
  'Godstime Awajiowa',
  'Gogo Bara',
  'Gogo Jonathan Caroline',
  'Gogo Michael Utonejit Offia',
  'Gogo Mkparo Iribe',
  'Goodfruit David',
  'Happiness Luke',
  'Harry Awajiobotumu',
  'Hebron Steven',
  'Hector Gladies',
  'Ibegbuna Iwari Okot Okot',
  'Igoni Afisia',
  'Igoni Afisia Lucky Ebirien',
  'Ikot-iye Jonathan',
  'Inene Idaso',
  'Inyene Martha Eriente',
  'Inyong Atanfut David',
  'Iribe Mkparo',
  'Isotu Frederick Sunday',
  'Ishmael Angelina',
  'Ite Lawrence Ephraim',
  'Josiah Ucheawaji',
  'Jacob Awaji- Imo',
  'Jessica Jack',
  'John (Laundry Man)',
  'Kasirotu Gwom-ibibaan',
  'Keziah Martins',
  'Keziah Martin',
  'Lawrence Ephraim',
  'Luke Oriadek A.',
  'Luke Happiness',
  'Manariah(Ekor) Wari Eugene',
  'Marcus Joe',
  'Mark Patience',
  'Martins Keziah',
  'Maxwell Gilbert',
  'Micah Fynecountry',
  'Micah Micah Fynecountry',
  'Miracle Daniel',
  'Monday Monday Christian',
  'Monday Ngofah',
  'Mr Iyaah Ubonmitop Gogo',
  'Mr Wari Eugene',
  'Mrs Arong Naomi',
  'Mrs Frank Hannah',
  'Mrs Iyaah Sarah Sasi',
  'Mrs Naaman Monica',
  'Nte Awajioreutoon',
  'Nte Margret',
  'Nkikpoawaji Umeh',
  'Nicholas Glory',
  'Nicholas Gogo',
  'Nicholas Osor',
  'Nichodemus David Samuel',
  'Ogwuamai Isidore Sokari Shedrack Gogo',
  'Ogwuama Ogwuafi Ejit',
  'Ogwuama Ogwuafi Francisca',
  'Ogwuomia Peace',
  'Oke Cyprian',
  'Okauwu Victory Loveday',
  'Oka-uwu Loveday Emmanuel',
  'Okwusi Sunday',
  
  'Opada Godson Garrick',
  'Opada Mercy Garrick',
  'Opoada Evelyn',
  'Oron Isaac',
  'Oron Miracle',
  'Oron Moses',
  'Oroku Otu-okwun Ogwem-ikweek',
  'Ottoo Roata',
  'Otuji Oboada Jumbo',
  'Patrick Ucheawaji',
  'Philip Philip',
  'Princess M.',
  'Recheal Adaibo',
  'Rose Ebirien-uket',
  'Rowland Awaji-igbe',
  'Ruth Dandison Abbey',
  'Samuel Awaji-mokot Elijah',
  'Sampson Edidiong John',
  'Savior Jesus',
  'Sokari Shedrack Gogo',
  'Sokari  Isidore  Shedrack',
  'Solomon Ngere',
  'Stephen Gogo Egbe',
  'Sunny',
  'Trust Martins O.',
  'Ucheawaji Awajiowa',
  'Ucheawaji Jerome',
  'Ucheawaji Patrick',
  'Uchente Ataisi Eneawaji',
  'Ugbanawaji Ene',
  'Ukwuoma Walter Ogwuichen',
  'Umeh Nkikpoawaji',
  'Uriah Lily',
  'Uriah Miracle',
  'Victor Kpanmgbore',
  'Wilson Ataeje',
  'Zebulon Zebulon'
]